### ISSUE TITLE
Can we have an anti-drag option for the left click dropper?

### ISSUE THREAD

**Issue by Duradel** [JZomerlei/zom-external-plugins#1]
As title says :)

**Comment by JZomerlei** [comment]
I will look into this. Should be allowed due to the nature of this plugin not being able to be abused for anything but dropping things.

Thanks for using my plugin.

**Comment by ymaerc** [comment]
Hey, how is the list organized? I've added a bunch of items since wildcarding doesn't seem to work, but since adding them all, it doesn't filter them, only the first item in the list left click drops. 
I've tried comma separation and breaks, and both combined.

**Comment by JZomerlei** [comment]
@Duradel I tink https://github.com/JZomerlei/zom-external-plugins/commit/2b3137d922b4118e5b5027b51ec81473963fc98b will be adding this feature.

**Comment by JZomerlei** [comment]
Done. Sorry about delay.

**Comment by Duradel** [comment]
Thanks man, really nice to have while training on 2 accounts :)

**Comment by JZomerlei** [comment]
It was harder than i thought but it is perfect now! Thanks for your advice because I love losing my own plugin now lol
