### ISSUE TITLE
Duplicate item entries in the item list break the drop functionality

### ISSUE THREAD

**Issue by afaber3** [JZomerlei/zom-external-plugins#3]
Just an FYI.  I typed "Raw trout" again but I meant to write "Raw salmon". XD
(A 3rd entry w/ makes the item left click drop again. Maybe it's not a bug it's a feature?)

**Comment by afaber3** [comment]
Edit: Just saw the closed issues thread. Would/can you add the list format to the readme, or the github landing page? Also, it seems the answer you gave is no longer up to date. It allows for spaces after the comma. Additionally, line carriages are also supported.

(HAHAHA your example in  the closed thread is exactly what I was doing... Great minds... Thanks for your work!)

**Comment by JZomerlei** [comment]
The repeated items should have no issues, if doesn’t reduce the list but checks for raw trout or what ever twice. 

I also introduced the feature to allow it to auto change item1, item2 into item1,item2 without issues. 

Thanks for losing my plugin.
