### ISSUE TITLE
Conflict with Shift Anti Drag

### ISSUE THREAD

**Issue by satyrsaw** [JZomerlei/zom-external-plugins#5]
While having "Custom Left Click Drop" ON, the normal Shift Anti-Drag does not work. Would it be possible to fix it?

**Comment by JZomerlei** [comment]
I will work on this.

**Comment by JZomerlei** [comment]
I got a fix but it’s very bad. It’s not going to be perfect. 

I don’t think anything I can do will make all users happy. What I think peoples should do in the mean time is turn off the plugin while you want to left click drop. 

I’m not giving up but it’s going to take a bit for a perfect solution.

**Comment by JZomerlei** [comment]
Added a disclaimer.
